# -*- coding: utf-8 -*-
# -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.#

# * File Name : compute_htn.py
#
# * Purpose :
#
# * Creation Date : 22-05-2024
#
# * Last Modified : Sunday 26 May 2024 12:08:30 PM
#
# * Created By : Yaay Nands
# _._._._._._._._._._._._._._._._._._._._._.#
import numpy as np
from numba import njit, float64

# custom imports
import params


def calculateGpi(htn):
    """
    Calculate the generated power for each grid cell.

    This function computes the power output for each grid cell by multiplying
    the given hourly thermal energy (HTN) with constants representing panel
    size, panel energy efficiency, and grid cell area.
    """
    return htn * params.PANEL_SIZE * params.PANEL_ENERGY_EFF * params.GRIDCELL_AREA


def calculateGpiPoly(gti_grid, time_and_day_arr, latitude, tilt_roof, ori_roof, valid_mask):
    """Returns layout for every timestep of energy generated by each valid gridcell"""
    time_arr = time_and_day_arr.timeArr
    day_arr = time_and_day_arr.dayArr
    poly_shape = gti_grid.shape
    gti_gridcellwise = gti_grid.reshape((time_arr.shape[0], -1))

    htn_gridcellwise = computeHtnForEachGridHour(day_arr, time_arr, latitude, tilt_roof, ori_roof, gti_gridcellwise)
    htn_grid = htn_gridcellwise.reshape(poly_shape)
    gpi_grid = calculateGpi(htn_grid)
    return gpi_grid


def calculateGpiPolyF(gti_grid, time_and_day_arr, latitude, tilt_roof, ori_roof, valid_mask):
    """Same as calculateGpiPoly, but avoids running computeHtnForEachGridHour for
    invalid panel positions"""
    time_arr = time_and_day_arr.timeArr
    day_arr = time_and_day_arr.dayArr
    valid_mask1 = valid_mask == 0
    c_gti_grid = np.moveaxis(gti_grid, 0, 2)
    valid_gti_gridcellwise = c_gti_grid[valid_mask1].T

    valid_htn_gridcellwise = computeHtnForEachGridHour(day_arr, time_arr, latitude, tilt_roof,
                                                       ori_roof, valid_gti_gridcellwise)
    htn_grid = np.zeros_like(c_gti_grid)
    htn_grid[valid_mask1] = valid_htn_gridcellwise.T
    ahtn_grid = np.moveaxis(htn_grid, 2, 0)
    gpi_grid = calculateGpi(ahtn_grid)
    return gpi_grid


def calculateCUF(generation, numberOfPanels):
    """
        Calculate the Capacity Utilization Factor (CUF) for a solar panel system.

        The CUF is determined by dividing the actual energy generation by the
        maximum possible energy generation over a year, given the number of panels
        and their wattage.

    """
    return generation / (params.PANEL_WATTAGE * 8760 * numberOfPanels)


@njit([(float64[:, :], float64, float64)], cache=True)
def boundingFuncA(arr, lowerb, upperb):
    """
        Constrain the values in a 2D array to lie within specified bounds.
    """
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr[i, j] > upperb:
                arr[i, j] = upperb
            elif arr[i, j] < lowerb:
                arr[i, j] = lowerb


@njit([(float64[:], float64, float64)], cache=True)
def boundingFuncB(arr, lowerb, upperb):
    """
     Constrain the values in a 1D array to lie within specified bounds.
    """
    for i in range(arr.shape[0]):
        if arr[i] > upperb:
            arr[i] = upperb
        elif arr[i] < lowerb:
            arr[i] = lowerb


@njit([(float64[:, :], float64[:, :], float64[:])], cache=True)
def processDiffuseRadiation(darr, carr, cl_index_poly_coeffs):
    """
    Calculate the diffuse radiation ratio for each element in the input arrays.

    This function processes the clearness index array `carr` using polynomial
    coefficients `cl_index_poly_coeffs` to compute the diffuse radiation ratio,
    which is stored in the output array `darr`. The calculation is based on
    different conditions of the clearness index values.

    """
    for i in range(carr.shape[0]):
        for j in range(carr.shape[1]):
            if carr[i, j] >= 0.8:
                darr[i, j] = 0.165
            elif carr[i, j] < 0.22:
                darr[i, j] = 1 - 0.009 * carr[i, j]
            else:
                acc = 0
                term = 1
                val = carr[i, j]
                for inx in range(len(cl_index_poly_coeffs)):
                    cli = cl_index_poly_coeffs[inx]
                    term *= val
                    acc += cli * term
                darr[i, j] = acc


# * 1.6
# 1.6 added this has to be removed after solar radiation is finalized

#
# Compute htn value for each grid hour value
#
def computeHtnForEachGridHour(dayOfYear, timeOfDay, latitude, tilt_panel, orientation_roof, tilt_irradiance_roof):
    """
    Compute the hourly irradiance on a tilted panel for each grid cell.

    This function calculates the solar irradiance received by a tilted panel
    at each grid cell, taking into account the day of the year, time of day,
    latitude, panel tilt, and roof orientation. It computes the beam, diffuse,
    and reflected components of solar radiation and applies bounding functions
    to ensure values remain within realistic limits.
    """
    decl = (23.45 * np.sin(np.radians(360 * (284 + dayOfYear) / 365)))
    omega = (15 * (timeOfDay - 12))

    rad_lat = np.radians(latitude)
    rad_tilt = np.radians(tilt_panel)
    rad_decl = np.radians(decl)
    rad_orient = np.radians(orientation_roof)
    rad_omega = np.radians(omega)

    sin_phi = np.sin(rad_lat)
    cos_phi = np.cos(rad_lat)
    sin_delta = np.sin(rad_decl)
    cos_beta = np.cos(rad_tilt)
    sin_beta = np.sin(rad_tilt)
    cos_delta = np.cos(rad_decl)
    cos_gamma = np.cos(rad_orient)
    sin_gamma = np.sin(rad_orient)
    cos_omega = np.cos(rad_omega)
    sin_omega = np.sin(rad_omega)

    expr1_cos_theta = sin_phi * ((sin_delta * cos_beta) + (cos_delta * cos_gamma * cos_omega * sin_beta))
    expr2_cos_theta = cos_phi * ((cos_delta * cos_omega * cos_beta) - (sin_delta * cos_gamma * sin_beta))
    expr3_cos_theta = cos_delta * sin_omega * sin_gamma * sin_beta
    cos_theta = expr1_cos_theta + expr2_cos_theta + expr3_cos_theta

    cos_thetaz = (sin_phi * sin_delta) + (cos_phi * cos_delta * cos_omega)
    solar_distance_factor = (np.cos(np.radians((360 / 365.0) * dayOfYear)) * 0.033) + 1
    extraterrestrial_radiation = params.SOLAR_CONSTANT * solar_distance_factor
    extraterrestrial_normal_radiation = cos_thetaz * extraterrestrial_radiation

    clearness_index = tilt_irradiance_roof / extraterrestrial_normal_radiation[:, np.newaxis]
    boundingFuncA(clearness_index, 0.0, 1.0)

    diffuse_radiation_ratio_GHI = np.empty_like(tilt_irradiance_roof, dtype=np.float64)
    cl_index_poly_coeffs = np.array([0.9511, -0.1604, 4.388, -16.638, 12.336])
    processDiffuseRadiation(diffuse_radiation_ratio_GHI, clearness_index, cl_index_poly_coeffs)

    diffuse_radiation = diffuse_radiation_ratio_GHI * tilt_irradiance_roof
    # diffuse_radiation=np.where(diffuse_radiation > 1367, 0, diffuse_radiation)
    boundingFuncA(diffuse_radiation, 0.0, np.inf)

    beam_radiation = tilt_irradiance_roof - diffuse_radiation
    boundingFuncA(beam_radiation, 0.0, np.inf)

    # beam_radiation=np.where(beam_radiation > 1367, 0, beam_radiation)
    tiltfactor_beam_radiation = cos_theta / cos_thetaz
    # tiltfactor_beam_radiation=np.where(tiltfactor_beam_radiation > 1367, 0, tiltfactor_beam_radiation)
    boundingFuncB(tiltfactor_beam_radiation, 0.0, np.inf)

    tiltfactor_diffuse_radiation = (1 + cos_beta) / 2
    # tiltfactor_diffuse_radiation=np.where(tiltfactor_diffuse_radiation > 1367, 0, tiltfactor_diffuse_radiation)
    tiltfactor_diffuse_radiation = max(tiltfactor_diffuse_radiation, 0)

    tiltfactor_reflected_radiation = ((1 - cos_beta) / 2) * params.ROOF_ALBEDO
    # tiltfactor_reflected_radiation=np.where(tiltfactor_reflected_radiation > 1367, 0, tiltfactor_reflected_radiation)
    tiltfactor_reflected_radiation = max(tiltfactor_reflected_radiation, 0)

    tilt_irradiance_panel = (tiltfactor_reflected_radiation * tilt_irradiance_roof) + (
            tiltfactor_diffuse_radiation * diffuse_radiation) + (
                                    tiltfactor_beam_radiation[:, np.newaxis] * beam_radiation)
    np.around(tilt_irradiance_panel, 2, out=tilt_irradiance_panel)
    boundingFuncA(tilt_irradiance_panel, 0.0, params.SOLAR_CONSTANT)

    return tilt_irradiance_panel


def computeTrig(dayOfYear, timeOfDay, latitude, tilt_panel, orientation_roof):
    """
    Compute trigonometric values related to solar panel orientation.

    This function calculates the solar declination, hour angle, and various
    trigonometric components based on the given day of the year, time of day,
    latitude, tilt of the solar panel, and orientation of the roof. It returns
    the cosine of the angle of incidence (cos_theta), the cosine of the zenith
    angle (cos_thetaz), and the cosine of the tilt angle (cos_beta).

    """
    decl = (23.45 * np.sin(np.radians(360 * (284 + dayOfYear) / 365)))
    omega = (15 * (timeOfDay - 12))

    rad_lat = np.radians(latitude)
    rad_tilt = np.radians(tilt_panel)
    rad_decl = np.radians(decl)
    rad_orient = np.radians(orientation_roof)
    rad_omega = np.radians(omega)

    sin_phi = np.sin(rad_lat)
    cos_phi = np.cos(rad_lat)
    sin_delta = np.sin(rad_decl)
    cos_beta = np.cos(rad_tilt)
    sin_beta = np.sin(rad_tilt)
    cos_delta = np.cos(rad_decl)
    cos_gamma = np.cos(rad_orient)
    sin_gamma = np.sin(rad_orient)
    cos_omega = np.cos(rad_omega)
    sin_omega = np.sin(rad_omega)

    expr1_cos_theta = sin_phi * ((sin_delta * cos_beta) + (cos_delta * cos_gamma * cos_omega * sin_beta))
    expr2_cos_theta = cos_phi * ((cos_delta * cos_omega * cos_beta) - (sin_delta * cos_gamma * sin_beta))
    expr3_cos_theta = cos_delta * sin_omega * sin_gamma * sin_beta
    cos_theta = expr1_cos_theta + expr2_cos_theta + expr3_cos_theta

    cos_thetaz = (sin_phi * sin_delta) + (cos_phi * cos_delta * cos_omega)
    return cos_theta, cos_thetaz, cos_beta


def computeHtnSepComp(cos_theta, cos_thetaz, cos_beta, beam_irradiance, diffuse_irradiance, shadow_map):
    """
    Calculate the incident solar radiation on a panel considering beam, diffuse, and reflected components.

    This function computes the solar radiation incident on a tilted panel by taking into account
    the tilt factors for beam, diffuse, and reflected radiation. It also considers the effect of
    shadows on the beam irradiance.

    """
    tiltfactor_beam_radiation = cos_theta / cos_thetaz
    tiltfactor_diffuse_radiation = (1 + cos_beta) / 2
    tiltfactor_reflected_radiation = ((1 - cos_beta) / 2) * params.ROOF_ALBEDO

    shadowed_beam_radiation = beam_irradiance[:, np.newaxis] * shadow_map

    incident_solar_radiation_panel = (tiltfactor_reflected_radiation * (shadowed_beam_radiation + diffuse_irradiance)) \
                                     + (tiltfactor_diffuse_radiation * diffuse_irradiance) \
                                     + (tiltfactor_beam_radiation[:, np.newaxis] * shadowed_beam_radiation)

    return incident_solar_radiation_panel
