[Environment]
port = 5665
request_length = 1048576
response_length = 1048576

[Parameters]
panel_wattage = 500
grid_size = 0.5
panel_dimen = 2,1
panel_energy_eff = 0.2025
hyst_new_row = 0.10
# improvement in generation required to start a new row
hyst_new_clus = 0.15
# improvement in generation required to start a new cluster
min_panels_in_row = 3
# minimum number of panels required to be laid in a row
lat_lon_len_str = 26
# max length of string required to hold lat-long grid id
roof_albedo = 0.25
#reflectivity of roof
solar_constant = 1367.0
#average radiation received outside earth's atmosphere
mount_height_multipliers = 1.,1.,1.,1.
#assumed radiation increase due to panels heights
