services:
  postgres:
    image: postgres:15
    container_name: mca_prefect_db
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d prefect"]
      interval: 5s
      timeout: 5s
      retries: 5

  prefect-server:
    env_file:
      - .env
    build: .
    container_name: mca_prefect_server
    ports:
      - "127.0.0.1:4200:4200"
    depends_on:
      postgres:
        condition: service_healthy
    command: |
      sh -c "
      prefect server start --host 0.0.0.0 &
      
      echo 'Waiting for Prefect Server API to become available...'
      until curl -s http://localhost:4200/api/health | grep -q 'true'; do
          sleep 1
      done
      
      echo 'Prefect Server is up! Running initialization script...'
      python /app/init_prefect.py
      wait
      "
    
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      - PREFECT_HOME=/root/.prefect
      - PREFECT_SERVER_API_AUTH_STRING=${PREFECT_API_KEY}
      # - PREFECT_SERVER_API_CSRF_PROTECTION_ENABLED=true
      # - PREFECT_SERVER_CSRF_PROTECTION_ENABLED=true
      - PREFECT_UI_API_URL=http://localhost:80/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_API_AUTH_STRING=${PREFECT_API_KEY}
      - PREFECT_CLIENT_CSRF_SUPPORT_ENABLED=true



    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mca_prefect_serve_flows:
    env_file:
      - .env
    build: .
    container_name: mca_prefect_worker
    depends_on:
      prefect-server:
        condition: service_healthy
    command: python deploy_flows.py
    environment:
      - PREFECT_HOME=/root/.prefect
      - PREFECT_API_URL=http://nginx_ingress:80/api
      - PREFECT_API_AUTH_STRING=${PREFECT_API_KEY}
      - PREFECT_CLIENT_CSRF_SUPPORT_ENABLED=true

      # Specify env variables here
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pgdata:/var/lib/postgresql/data
      - C:\:/app/data/c_drive
      # - Z:\:/app/data/z_drive
      - smb_z_share:/app/data/z_drive
    restart: "no"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy

    dns:
      - 127.0.0.11
      - 8.8.8.8
      - 1.1.1.1
    
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${APP_CLIENT_ID}
      - OAUTH2_PROXY_AZURE_TENANT=${APP_TENANT_ID}
      
      # Dynamically construct the issuer URL using your tenant variable
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/${APP_TENANT_ID}/v2.0
      
      # Keep your remaining default variables intact
      - OAUTH2_PROXY_CLIENT_SECRET=${APP_SECRET}
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_COOKIE_SECRET=PZcUXnnf4fNP7tzccgXBwZACpXvPDXn7
      - OAUTH2_PROXY_UPSTREAMS=http://prefect-server:4200
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=cstep.in
  
  nginx-gate:
    image: nginx:latest
    container_name: nginx_ingress
    ports:
      - "80:80"
    env_file:
    - .env
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh:ro  
    entrypoint: ["/bin/sh", "/nginx-entrypoint.sh", "${PREFECT_API_KEY}"]
    depends_on:
          prefect-server:
            condition: service_started
          oauth2-proxy:
            condition: service_started


volumes:
  pgdata:
  smb_z_share:
    driver: local
    driver_opts:
      type: cifs
      # Replace with your actual share address, username, and password
      device: "//172.16.0.138/edall/"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},file_mode=0777,dir_mode=0777,iocharset=utf8"
  
  